# Generated by Django 5.2.9 on 2026-05-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapeamentoDePara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_extrato', models.CharField(max_length=255, unique=True, verbose_name='Descrição no Extrato')),
                ('cnpj_cpf', models.CharField(max_length=18, verbose_name='CNPJ/CPF Correspondente')),
                ('nome_cliente', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome/Razão Social')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapeamento De-Para',
                'verbose_name_plural': 'Mapeamentos De-Para',
            },
        ),
        migrations.CreateModel(
            name='ExtratoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('2', '2 - Protege Proteção e Transporte de Valores'), ('4', '4 - Proair Serviços Aux. de Transporte Aereo'), ('5', '5 - Provig Form de Profissionais de Segurança'), ('50', '50 - Protege Cargo Transportadora'), ('6', '6 - Protege Segurança Eletronica'), ('7', '7 - Protege Serviços Especiais'), ('80', '80 - Portaria do Futuro')], max_length=5, verbose_name='Empresa')),
                ('conta_corrente', models.CharField(max_length=30, verbose_name='Conta Corrente')),
                ('banco', models.CharField(choices=[('ITAU', 'Itaú'), ('BRADESCO', 'Bradesco')], max_length=20)),
                ('data_transacao', models.DateField()),
                ('descricao', models.CharField(max_length=255, verbose_name='Lançamento')),
                ('documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dcto.')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_conta', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cnpj_cpf', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ/CPF Identificado')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social Identificada')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (Sem match)'), ('CONCILIADO_PARCIAL', 'Conciliado Parcialmente'), ('CONCILIADO', 'Conciliado 100%'), ('IGNORADO', 'Ignorado/Tarifa Bancária')], default='PENDENTE', max_length=30)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Extrato Bancário',
                'verbose_name_plural': 'Extratos Bancários',
                'unique_together': {('empresa', 'banco', 'conta_corrente', 'data_transacao', 'descricao', 'documento', 'valor', 'saldo_conta')},
            },
        ),
    ]
