# Generated by Django 5.2.9 on 2026-05-27 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0025_alter_excecao_raiz_cnpj'),
        ('conciliacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacaoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Pago da Nota')),
                ('impostos_retidos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Impostos Retidos no Pagto')),
                ('data_conciliacao', models.DateTimeField(auto_now_add=True)),
                ('extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacoes', to='conciliacao.extratobancario', verbose_name='Extrato Bancário')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes', to='analise.basegeral', verbose_name='Nota Fiscal (Base Geral)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota Conciliada',
                'verbose_name_plural': 'Notas Conciliadas',
                'unique_together': {('extrato', 'nota')},
            },
        ),
    ]
