# Generated by Django 5.2.9 on 2026-05-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0026_contasreceber'),
        ('conciliacao', '0002_conciliacaonota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conciliacaonota',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes', to='analise.contasreceber', verbose_name='Nota Fiscal'),
        ),
    ]
