# Generated by Django 5.2.9 on 2026-05-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacao', '0003_alter_conciliacaonota_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcecaoConciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=255, unique=True, verbose_name='Termo Ignorado (Contém)')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo/Observação')),
            ],
            options={
                'verbose_name': 'Exceção de Importação',
                'verbose_name_plural': 'Exceções de Importação',
            },
        ),
    ]
