# Generated by Django 5.2.9 on 2026-06-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacao', '0004_excecaoconciliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoNaoDestinado',
            fields=[
                ('dni', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='DNI')),
                ('data', models.DateField(verbose_name='Data')),
                ('estab', models.IntegerField(verbose_name='Estabelecimento')),
                ('credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Crédito')),
                ('debitos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Débitos')),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Final')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('banco', models.CharField(max_length=5, verbose_name='Banco')),
                ('empresa', models.CharField(max_length=15, verbose_name='Empresa')),
            ],
        ),
    ]
