# Generated by Django 5.2.9 on 2026-06-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacao', '0005_creditonaodestinado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_busca', models.CharField(max_length=25, unique=True, verbose_name='CNPJ da Busca')),
                ('email', models.CharField(max_length=255, verbose_name='E-mails (Separados por ponto e vírgula)')),
            ],
        ),
        migrations.CreateModel(
            name='EstabelecimentoCNPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estab', models.IntegerField(unique=True, verbose_name='Estabelecimento')),
                ('nome_empresa', models.CharField(max_length=150, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=25, verbose_name='CNPJ')),
            ],
        ),
    ]
