# Generated by Django 5.2.9 on 2026-06-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0027_creditonaodestinado_observacao'),
        ('conciliacao', '0007_creditonaodestinado_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratobancario',
            name='cor_automacao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor da Automação'),
        ),
        migrations.CreateModel(
            name='SugestaoAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_sugerido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_automacao', to='conciliacao.extratobancario')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analise.contasreceber')),
            ],
            options={
                'verbose_name': 'Sugestão de Automação',
                'verbose_name_plural': 'Sugestões de Automação',
            },
        ),
    ]
