# Generated by Django 5.2.9 on 2025-12-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoIgnorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Código Ignorado',
                'verbose_name_plural': 'Códigos Ignorados',
                'db_table': 'CodigosIgnorados',
            },
        ),
    ]
