# Generated by Django 5.2.9 on 2025-12-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresasCorporativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
            ],
            options={
                'verbose_name': 'Empresa Corporativa',
                'verbose_name_plural': 'Empresas Corporativas',
                'db_table': 'EmpresasCorporativas',
            },
        ),
    ]
