# Generated by Django 5.2.9 on 2025-12-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0002_empresascorporativas'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegocioCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Negócio Corporativo',
                'verbose_name_plural': 'Negócios Corporativos',
                'db_table': 'NegocioCorporativo',
            },
        ),
        migrations.CreateModel(
            name='ResponsavelEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=150, verbose_name='Empresa')),
                ('carteira', models.CharField(max_length=150, verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Responsável por Empresa',
                'verbose_name_plural': 'Responsáveis por Empresas',
                'db_table': 'ResponsavelEmpresa',
            },
        ),
        migrations.CreateModel(
            name='ResponsavelNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negocio', models.CharField(max_length=150, verbose_name='Negócio')),
                ('carteira', models.CharField(max_length=150, verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Responsável por Negócio',
                'verbose_name_plural': 'Responsáveis por Negócios',
                'db_table': 'ResponsavelNegocio',
            },
        ),
    ]
