# Generated by Django 5.2.9 on 2025-12-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0003_negociocorporativo_responsavelempresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurCargaSegura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiz', models.CharField(max_length=15, verbose_name='Raiz')),
                ('razao', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('perfil', models.CharField(max_length=100, verbose_name='Perfil')),
                ('negocio', models.CharField(max_length=50, verbose_name='Negócio')),
                ('chave', models.CharField(max_length=150, verbose_name='Chave')),
                ('executivo', models.CharField(max_length=50, verbose_name='Executivo')),
                ('responsavel_financeiro', models.CharField(max_length=50, verbose_name='Responsável Financeiro')),
                ('grupo', models.CharField(max_length=100, verbose_name='Grupo')),
                ('status', models.CharField(max_length=15, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Jur Carga Segura',
                'verbose_name_plural': 'Jur Carga Segura',
                'db_table': 'JurCargaSegura',
            },
        ),
    ]
