# Generated by Django 5.2.9 on 2025-12-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0004_jurcargasegura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paycash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=30, verbose_name='Chave')),
                ('dt_emissao_fatura', models.DateField(verbose_name='DT.Emissao Fatura')),
                ('estabelecimento', models.IntegerField(verbose_name='Estabelecimento')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('nro_fatura', models.IntegerField(verbose_name='Nro Fatura')),
                ('serie', models.CharField(max_length=5, verbose_name='Série')),
                ('rps', models.IntegerField(verbose_name='RPS')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Paycash',
                'verbose_name_plural': 'Paycash',
                'db_table': 'Paycash',
            },
        ),
    ]
