# Generated by Django 5.2.9 on 2025-12-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0005_paycash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bd_Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_raiz', models.CharField(max_length=30, verbose_name='CNPJ_Raiz')),
                ('razao_social', models.CharField(max_length=250, verbose_name='Razão_Social')),
                ('perfil_fatura', models.CharField(max_length=50, verbose_name='Perfil Fatura')),
                ('perfil_negocio', models.CharField(max_length=50, verbose_name='Perfil Negocio')),
                ('perfil_chave', models.CharField(max_length=100, verbose_name='Perfil Chave')),
                ('perfil_executivo', models.CharField(max_length=150, verbose_name='Perfil Executivo')),
                ('perfil_responsavel_financeiro', models.CharField(max_length=20, verbose_name='Perfil Responsavel_Financeiro')),
                ('perfil_grupo_ponto', models.CharField(max_length=50, verbose_name='Perfil Grupo_Ponto')),
                ('perfil_status', models.CharField(max_length=10, verbose_name='Perfil Status')),
            ],
            options={
                'verbose_name': 'BD Cliente',
                'verbose_name_plural': 'BD Clientes',
                'db_table': 'Bd_Clientes',
            },
        ),
    ]
