# Generated by Django 5.2.9 on 2025-12-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0006_bd_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consolidado_Juridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=20, verbose_name='Chave')),
                ('classificacao', models.CharField(max_length=50, verbose_name='Classificação')),
                ('estabelec', models.CharField(max_length=5, verbose_name='Estabelec')),
                ('serie', models.CharField(max_length=5, verbose_name='Série')),
                ('titulo', models.IntegerField(verbose_name='Título')),
                ('unid_neg', models.CharField(max_length=5, verbose_name='Unid_Neg')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('cnpj_cpf_cliente', models.CharField(max_length=25, verbose_name='CNPJ/CPF_Cliente')),
                ('grupo', models.CharField(max_length=50, verbose_name='Grupo')),
                ('nome_abrev', models.CharField(max_length=150, verbose_name='Nome_Abrev')),
                ('dt_emissao_orig', models.DateField(verbose_name='Dt.Emissão Orig')),
                ('dt_vencto_original', models.DateField(verbose_name='Dt.Vencto Original')),
                ('vl_bruto_orig', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Vl.Bruto Orig.')),
                ('vl_liquido', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Vl.líquido')),
            ],
            options={
                'verbose_name': 'Consolidado Jurídico',
                'verbose_name_plural': 'Consolidado Jurídico',
                'db_table': 'Consolidado_Juridico',
            },
        ),
    ]
