# Generated by Django 5.2.9 on 2025-12-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0007_consolidado_juridico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidado_juridico',
            name='dt_emissao_orig',
            field=models.DateField(blank=True, null=True, verbose_name='Dt.Emissão Orig'),
        ),
        migrations.AlterField(
            model_name='consolidado_juridico',
            name='dt_vencto_original',
            field=models.DateField(blank=True, null=True, verbose_name='Dt.Vencto Original'),
        ),
    ]
