# Generated by Django 5.2.9 on 2026-01-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0009_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.CharField(max_length=4, verbose_name='Estabelec')),
                ('especie', models.CharField(max_length=3, verbose_name='Espécie')),
                ('serie', models.CharField(max_length=5, verbose_name='Série')),
                ('titulo', models.BigIntegerField(verbose_name='Título')),
                ('parcela', models.CharField(max_length=3, verbose_name='Parcela')),
                ('dt_emissao_orig', models.DateField(verbose_name='Dt.Emissão Orig')),
                ('dt_emissao_ult_ren', models.DateField(blank=True, null=True, verbose_name='Dt.Emissão Últ.Ren')),
                ('dt_vencto_original', models.DateField(verbose_name='Dt.Vencto Original')),
                ('dt_vencto_atual', models.DateField(verbose_name='Dt.Vencto Atual')),
                ('estab_dest', models.CharField(blank=True, max_length=4, null=True, verbose_name='Estab.Dest')),
                ('c_custo_dest', models.CharField(blank=True, max_length=4, null=True, verbose_name='C.Custo.Dest')),
                ('empresa', models.CharField(max_length=3, verbose_name='Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('cnpj_cpf_cliente', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ/CPF Cliente')),
                ('codigo', models.BigIntegerField(verbose_name='Código')),
                ('nome_abrev', models.CharField(max_length=250, verbose_name='Nome Abrev')),
                ('vl_bruto_reneg', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Vl.Bruto Reneg.')),
                ('vl_bruto_orig', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Vl.Bruto Orig.')),
                ('pis', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='PIS')),
                ('cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cofins')),
                ('csll', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='CSLL')),
                ('irrf', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='IRRF')),
                ('iss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='ISS')),
                ('inss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='INSS')),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Desconto')),
                ('liquidacao', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Liquidacao')),
                ('acerto', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Acerto')),
                ('conta_contabil', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Conta Contabil')),
                ('multa', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Multa')),
                ('juros', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Juros')),
                ('vl_liq_orig', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Vl.Liq.Orig')),
                ('vl_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Vl.Líquido')),
                ('carteira', models.CharField(max_length=2, verbose_name='Carteira')),
                ('unid_negoc', models.CharField(max_length=4, verbose_name='Unid.Negoc')),
                ('cnpj_estab', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ Estab.')),
                ('gr_cli', models.CharField(blank=True, max_length=5, null=True, verbose_name='Gr. Cli')),
                ('descricao_gr_cli', models.CharField(blank=True, max_length=20, null=True, verbose_name='Descrição Gr. Cli.')),
                ('posicao_da_regua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Posição da Régua')),
                ('usuario_regua', models.CharField(blank=True, max_length=20, null=True, verbose_name='Usuário Régua')),
                ('ultima_movimentacao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Última Movimentação')),
                ('responsavel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Responsável')),
                ('motivo_renegociacao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Motivo Renegociaço')),
                ('nosso_numero', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nosso Número')),
                ('portador', models.CharField(blank=True, max_length=5, null=True, verbose_name='Portador')),
                ('observacao_nota', models.CharField(blank=True, max_length=15, null=True, verbose_name='Observação Nota')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
