# Generated by Django 5.2.9 on 2026-02-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0011_alter_basegeral_data_importacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteSuspenso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Em Análise', max_length=15, verbose_name='Status')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('cnpj_raiz', models.CharField(max_length=12, verbose_name='CNPJ Raiz')),
                ('estabelecimento', models.CharField(max_length=30, verbose_name='Estabelecimento')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('data_suspensao', models.DateField(blank=True, null=True, verbose_name='Data Suspensão')),
                ('suspenso', models.CharField(blank=True, max_length=3, null=True, verbose_name='Suspenso')),
                ('data_restabelecimento', models.DateField(blank=True, null=True, verbose_name='Data Restabelecimento')),
                ('executivo', models.CharField(blank=True, max_length=150, null=True, verbose_name='EXECUTIVO')),
                ('inadimplencia2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Inadimplência2')),
                ('operacao_ultimo_atendimento', models.DateField(blank=True, null=True, verbose_name='Operação - Último Atendimento')),
                ('cancelado_flag', models.CharField(blank=True, max_length=3, null=True, verbose_name='Cancelado?')),
                ('data_cancelamento', models.DateField(blank=True, null=True, verbose_name='Data Cancelamento')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
