# Generated by Django 5.2.9 on 2026-02-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0012_clientesuspenso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesuspenso',
            name='data_cancelamento',
            field=models.CharField(blank=True, null=True, verbose_name='Data Cancelamento'),
        ),
        migrations.AlterField(
            model_name='clientesuspenso',
            name='data_restabelecimento',
            field=models.CharField(blank=True, null=True, verbose_name='Data Restabelecimento'),
        ),
        migrations.AlterField(
            model_name='clientesuspenso',
            name='data_suspensao',
            field=models.CharField(blank=True, null=True, verbose_name='Data Suspensão'),
        ),
        migrations.AlterField(
            model_name='clientesuspenso',
            name='operacao_ultimo_atendimento',
            field=models.CharField(blank=True, null=True, verbose_name='Operação - Último Atendimento'),
        ),
    ]
