# Generated by Django 5.2.9 on 2026-02-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0013_alter_clientesuspenso_data_cancelamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesuspenso',
            name='data_restabelecimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Restabelecimento'),
        ),
        migrations.AlterField(
            model_name='clientesuspenso',
            name='data_suspensao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Suspensão'),
        ),
    ]
