# Generated by Django 5.2.9 on 2026-02-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0014_alter_clientesuspenso_data_restabelecimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesuspenso',
            name='operacao_ultimo_atendimento',
            field=models.DateField(blank=True, null=True, verbose_name='Operação - Último Atendimento'),
        ),
    ]
