# Generated by Django 5.2.9 on 2026-03-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0015_alter_clientesuspenso_operacao_ultimo_atendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(verbose_name='Data da Foto')),
                ('categoria_painel', models.CharField(choices=[('RESUMO', 'Resumo Gerencial'), ('RENEGOCIACAO', 'Renegociações'), ('AGING_PACOTE', 'Aging Pacote'), ('NEGOCIO', 'Negócio'), ('EMPRESA', 'Empresa'), ('AGING', 'Aging'), ('AGING_JURIDICO', 'Aging Jurídico')], default='RESUMO', max_length=50)),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição/Métrica')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor R$')),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% (se houver)')),
                ('is_final_mes', models.BooleanField(default=False, verbose_name='É fechamento mensal?')),
            ],
            options={
                'verbose_name': 'Dado do Dashboard',
                'verbose_name_plural': 'Dados do Dashboard',
                'db_table': 'DashboardIndicadores',
                'ordering': ['-data_referencia', 'descricao'],
            },
        ),
    ]
