# Generated by Django 5.2.9 on 2026-03-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0016_dashboardindicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseHistoricaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateField(verbose_name='Data da Foto/Extração')),
                ('aba_origem', models.CharField(max_length=50, verbose_name='Aba de Origem')),
                ('regional', models.CharField(blank=True, max_length=100, null=True, verbose_name='Regional')),
                ('base_operacional', models.CharField(blank=True, max_length=100, null=True, verbose_name='Base Operacional')),
                ('estabelecimento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Estabelec')),
                ('especie', models.CharField(blank=True, max_length=5, null=True, verbose_name='Espécie')),
                ('serie', models.CharField(blank=True, max_length=10, null=True, verbose_name='Série')),
                ('titulo', models.BigIntegerField(blank=True, null=True, verbose_name='Título')),
                ('parcela', models.CharField(blank=True, max_length=5, null=True, verbose_name='Parcela')),
                ('unid_negoc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unid.Negoc')),
                ('negocio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Negócio')),
                ('empresa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Empresa')),
                ('carteira', models.CharField(blank=True, max_length=10, null=True, verbose_name='Carteira')),
                ('codigo', models.BigIntegerField(blank=True, null=True, verbose_name='Codigo')),
                ('pacote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pacote')),
                ('cnpj_raiz', models.CharField(blank=True, max_length=20, null=True, verbose_name='Raiz CNPJ')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=25, null=True, verbose_name='CNPJ/CPF Cliente')),
                ('razao_agrupada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Agrupada')),
                ('nome_abrev', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Abrev')),
                ('dt_emissao_orig', models.DateField(blank=True, null=True, verbose_name='Dt.Emissão Orig')),
                ('dt_emissao_ult_ren', models.DateField(blank=True, null=True, verbose_name='Dt.Emissão Últ.Ren')),
                ('dt_vencto_original', models.DateField(blank=True, null=True, verbose_name='Dt.Vencto Original')),
                ('dt_vencto_atual', models.DateField(blank=True, null=True, verbose_name='Dt.Vencto Atual')),
                ('vl_bruto_orig', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Vl.Bruto Orig.')),
                ('vl_liquido', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Vl.líquido')),
                ('dias_atraso', models.IntegerField(default=0, verbose_name='Dias em Atraso')),
                ('dias_atraso_re', models.IntegerField(default=0, verbose_name='Dias em Atraso RE')),
                ('aging', models.CharField(blank=True, max_length=50, null=True, verbose_name='Aging')),
                ('aging_re', models.CharField(blank=True, max_length=50, null=True, verbose_name='Aging RE')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Registro Histórico de Relatório',
                'verbose_name_plural': 'Registros Históricos de Relatório',
                'db_table': 'BaseHistoricaRelatorio',
                'indexes': [models.Index(fields=['data_geracao', 'aba_origem', 'unid_negoc'], name='BaseHistori_data_ge_d29ad9_idx')],
            },
        ),
    ]
