# Generated by Django 5.2.9 on 2026-03-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0017_basehistoricarelatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoInadimplencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguimento', models.CharField(max_length=150, verbose_name='Seguimento / Métrica')),
                ('data', models.DateField(verbose_name='Data de Referência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor R$')),
                ('tipo_relatorio', models.CharField(default='GERAL', max_length=50, verbose_name='Tipo de Relatório')),
            ],
            options={
                'verbose_name': 'Histórico de Resumo',
                'verbose_name_plural': 'Histórico de Resumos',
                'db_table': 'ResumoInadimplencia',
                'ordering': ['data', 'seguimento'],
                'unique_together': {('seguimento', 'data', 'tipo_relatorio')},
            },
        ),
    ]
