# Generated by Django 5.2.9 on 2026-03-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0018_resumoinadimplencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevedorAging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aging_tipo', models.CharField(max_length=100, verbose_name='Tipo de Aging')),
                ('ate_30_dias', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('de_31_a_60_dias', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('de_61_a_90_dias', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('de_91_a_120_dias', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('de_121_a_150_dias', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('de_151_a_180_dias', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mais_de_180_dias', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
            ],
            options={
                'verbose_name': 'Aging de Devedor',
                'verbose_name_plural': 'Aging de Devedores',
            },
        ),
    ]
