# Generated by Django 5.2.9 on 2026-03-18 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0019_devedoraging'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devedoraging',
            options={},
        ),
        migrations.RemoveField(
            model_name='devedoraging',
            name='aging_tipo',
        ),
        migrations.AddField(
            model_name='devedoraging',
            name='data_base',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Referência'),
            preserve_default=False,
        ),
    ]
