# Generated by Django 5.2.9 on 2026-03-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0020_alter_devedoraging_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devedoraging',
            name='data_base',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Referência'),
        ),
    ]
