# Generated by Django 5.2.9 on 2026-04-17 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0021_alter_devedoraging_data_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoNaoDestinado',
            fields=[
                ('dni', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='DNI')),
                ('data', models.DateField(verbose_name='Data')),
                ('estab', models.IntegerField(verbose_name='Estabelecimento')),
                ('credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Crédito')),
                ('debitos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Débitos')),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Final')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('banco', models.CharField(max_length=5, verbose_name='Banco')),
                ('empresa', models.CharField(max_length=15, verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAbatimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abatimento', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observacao', models.TextField(verbose_name='Como e onde foi abatido/devolvido')),
                ('credito_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abatimentos', to='analise.creditonaodestinado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contato', models.DateTimeField(auto_now_add=True)),
                ('anotacao', models.TextField(verbose_name='Histórico do Contato')),
                ('credito_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='analise.creditonaodestinado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_contato'],
            },
        ),
    ]
