# Generated by Django 5.2.9 on 2026-04-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0022_creditonaodestinado_historicoabatimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiz_cnpj', models.CharField(max_length=13, unique=True, verbose_name='Raiz CNPJ')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('nome_abrev', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome Abrev')),
                ('carteira', models.CharField(max_length=50, verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Exceções',
            },
        ),
    ]
