# Generated by Django 5.2.9 on 2026-04-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0023_excecao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excecao',
            options={'verbose_name': 'Exceção', 'verbose_name_plural': 'Exceções'},
        ),
        migrations.AddField(
            model_name='excecao',
            name='unid_negoc',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Unid.Negoc'),
        ),
    ]
