# Generated by Django 5.2.9 on 2026-04-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0024_alter_excecao_options_excecao_unid_negoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excecao',
            name='raiz_cnpj',
            field=models.CharField(max_length=13, verbose_name='Raiz CNPJ'),
        ),
    ]
