# Generated by Django 5.2.9 on 2026-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0025_alter_excecao_raiz_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.CharField(blank=True, max_length=10, null=True)),
                ('especie', models.CharField(blank=True, max_length=10, null=True)),
                ('serie', models.CharField(blank=True, max_length=20, null=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('parcela', models.CharField(blank=True, max_length=10, null=True)),
                ('dt_emissao_orig', models.DateField(blank=True, null=True)),
                ('dt_vencto_atual', models.DateField(blank=True, null=True)),
                ('empresa', models.CharField(blank=True, max_length=10, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_abrev', models.CharField(blank=True, max_length=255, null=True)),
                ('vl_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pis', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cofins', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('csll', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('irrf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('iss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('inss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('abatimento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vl_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('carteira', models.CharField(blank=True, max_length=20, null=True)),
                ('nosso_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('portador', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('segmento', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='ABERTO', max_length=20)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
            },
        ),
    ]
