# Generated by Django 5.2.9 on 2026-06-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0026_contasreceber'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditonaodestinado',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
